# Configuration of the study sessions.
# Used for personalizing content for individual participants.
#######################################################################
# For each session, we need to know the following:
#
# - What type of story is told each session? Either the robot tells a story and
#   the child is asked to retell it, or the child is asked to make up their own
#   story.
# - Does this session include a negotiation task? If so, we need to use it;
#   otherwise, we need to reference the previous sessions's negotiation.
# - Default scenes to use and stories to tell (for participants who don't get
#   personalized stories).
# - TODO add any more!
#######################################################################
# EXAMPLE SESSION
#######################################################################
#[sessions.sessionnum]
## The type of story to tell this session.
#story_type = "retell"
#
## The name of the story to tell this session, if we're doing a story retell.
#story_name = "BoyAndFrog"
#
## Whether this session has a negotiation task.
#negotiation = false
#
## The SR2 story scenes to show this session. You need to specify this if the
## story type is "create" since these are the scenes used for that.
#scenes = ["Iceberg", "Dinoville"]
#
## The number of scenes total that we will need to select for this session.
## This number can be bigger than the number of scenes specified above, since
## if not enough are specified, more scenes will be selected automatically.
## However, this number should not be bigger than the total number of scenes
## that are available.
#num_scenes = 2
#
## The SR2 story corpus to use this session.
#corpus = "SR2_robot"
#
## Whether to pick stories that are the most similar (true) or the least
## similar (false) as compared to the participant's stories.
#similar = true
#
## The stories to use as defaults for participants who don't get a set of
## personalized stories.
#default_stories = [ { scene = "Iceberg", story = "PenguinSlide" },
#                    { scene = "Treemeadow", story = "DragonClumsy" } ]
#######################################################################
[sessions.1]
story_type = "retell"
story_name = "baby_birds_first_nest"
negotiation = false

[sessions.2]
story_type = "create"
negotiation = true
scenes = ["Iceberg", "Playground"]
corpus = "SR2_robot"
num_scenes = 2
similar = true
default_scenes = ["Iceberg", "Castle"]
    [sessions.2.default_stories.Iceberg]
    story = "PenguinSlide"
    [sessions.2.default_stories.Castle]
    story = "ReshmaParty"

[sessions.3]
story_type = "create"
negotiation = false
corpus = "SR2_child"
num_scenes = 2
similar = false
default_scenes = ["Playground"]
    [sessions.3.default_stories.Iceberg]
    story = "Iceberg-sr2-session8-p006-story1"
    [sessions.3.default_stories.Playground]
    story = "Playground-sr2-session1-p006-story2"
    [sessions.3.default_stories.Castle]
    story = "Castle-sr2-session2-p015-story2"

[sessions.4]
story_type = "retell"
story_name = "possum_and_the_peeper"
negotiation = false

[sessions.5]
story_type = "retell"
story_name = "henrys_happy_birthday"
negotiation = false

[sessions.6]
story_type = "create"
negotiation = true
corpus = "SR2_robot"
num_scenes = 2
similar = true
default_scenes = ["Treemeadow"]
    [sessions.5.default_stories.Iceberg]
    story = "PenguinSlide"
    [sessions.5.default_stories.Treemeadow]
    story = "DragonClumsy"
    [sessions.5.default_stories.Playground]
    story = "PlayBall"
    [sessions.5.default_stories.Castle]
    story = "EvilKing"

[sessions.7]
story_type = "create"
negotiation = false
corpus = "SR2_child"
num_scenes = 2
similar = true
default_scenes = ["Pineforest"]
    [sessions.6.default_stories.Iceberg]
    story = "Iceberg-sr2-session8-p006-story1"
    [sessions.6.default_stories.Treemeadow]
    story = "Treemeadow-sr2-session8-p013-story1"
    [sessions.6.default_stories.Playground]
    story = "Playground-sr2-session1-p006-story2"
    [sessions.6.default_stories.Castle]
    story = "Castle-sr2-session2-p015-story2"
    [sessions.6.default_stories.Pineforest]
    story = "Pineforest-sr2-session2-p009-story1"

[sessions.8]
story_type = "retell"
story_name = "baby_ducks_new_friend"
negotiation = false

[sessions.9]
story_type = "create"
negotiation = true
corpus = "SR2_robot"
num_scenes = 2
similar = true
default_scenes = ["Dinoville"]
    [sessions.8.default_stories.Iceberg]
    story = "PenguinSlide"
    [sessions.8.default_stories.Treemeadow]
    story = "DragonClumsy"
    [sessions.8.default_stories.Playground]
    story = "PlayBall"
    [sessions.8.default_stories.Castle]
    story = "EvilKing"
    [sessions.8.default_stories.Pineforest]
    story = "FloppyHideSeek"
    [sessions.8.default_stories.Dinoville]
    story = "DinoEater"

[sessions.10]
story_type = "create"
negotiation = false
corpus = "SR2_child"
num_scenes = 2
similar = true
default_scenes = ["Mars"]
    [sessions.9.default_stories.Iceberg]
    story = "Iceberg-sr2-session8-p006-story1"
    [sessions.9.default_stories.Treemeadow]
    story = "Treemeadow-sr2-session8-p013-story1"
    [sessions.9.default_stories.Playground]
    story = "Playground-sr2-session1-p007-story2"
    [sessions.9.default_stories.Castle]
    story = "Castle-sr2-session2-p015-story2"
    [sessions.9.default_stories.Pineforest]
    story = "Pineforest-sr2-session2-p009-story1"
    [sessions.9.default_stories.Dinoville]
    story = "Dinoville-sr2-session4-p004-1-story1"
    [sessions.9.default_stories.Mars]
    story = "Mars-sr2-session3-p009-story2"


#######################################################################
# Lists of stories that the robot could tell. Each list should contain the
# names of the stories in that story corpus and the story scene for the story.
#
# If there are multiple levels of the stories available, specify how many, and
# if the levels have names, add those and the delimiter used so we can build
# the story file names later. For example, there might be stories such as
# "Castle-EvilKing-E" for the easy level of a story in the Castle scene, and
# "Castle-EvilKing-H" for the hard level.
#
# The stories for a given scene are nested under the scene name in case we
# want to also list more information about the scene under the scene name
# later, such as the vocabulary words for the scene or other information.
#######################################################################
[story_corpus.SR2_robot]
levels = [0, 1]
level_names = ["E", "H"]
delimiter = "-"
[story_corpus.SR2_robot.scenes.Castle]
stories = [ "EvilKing", "ReshmaParty" ]
[story_corpus.SR2_robot.scenes.Dinoville]
stories = [ "DinoEater", "ScaryDino" ]
[story_corpus.SR2_robot.scenes.House]
stories = [ "MagicShow", "SofaPirates" ]
[story_corpus.SR2_robot.scenes.Iceberg]
stories = [ "PenguinSlide", "SnowmanHat" ]
[story_corpus.SR2_robot.scenes.Mars]
stories = [ "AlienFather", "ExploreNew" ]
[story_corpus.SR2_robot.scenes.PineForest]
stories = [ "FloppyHideSeek", "TinnaFortune" ]
[story_corpus.SR2_robot.scenes.Playground]
stories = [ "PlayBall", "PlayPretend" ]
[story_corpus.SR2_robot.scenes.Treemeadow]
stories = [ "DragonClumsy", "BirdButterfly" ]

[story_corpus.SR2_child]
levels = [0]
level_names = [""]
delimiter = "-"
[story_corpus.SR2_child.scenes.Castle]
stories = [ "sr2-session1-p013-story2", "sr2-session2-p004-story2", "sr2-session2-p006-story2", "sr2-session2-p007-story2", "sr2-session2-p009-story2", "sr2-session2-p010-story2", "sr2-session2-p015-story2", "sr2-session6-p004-story1", "sr2-session6-p006-story1", "sr2-session6-p007-story1", "sr2-session6-p013-story2"]
[story_corpus.SR2_child.scenes.Dinoville]
stories = [ "sr2-session4-p004-1-story1", "sr2-session4-p006-1-story1", "sr2-session4-p007-story1", "sr2-session4-p009-1-story1", "sr2-session6-p004-story2", "sr2-session6-p006-story2", "sr2-session6-p011-story2"]
[story_corpus.SR2_child.scenes.House]
stories = [ "sr2-session2-p013-story2", "sr2-session3-p006-story1", "sr2-session3-p007-story1", "sr2-session3-p009-story1", "sr2-session4-p013-story1", "sr2-session7-p006-story2", "sr2-session7-p007-story2", "sr2-session7-p009-story2", "sr2-session7-p013-story2", "sr2-session7-p015-story2", "sr2-session8-p013-story2"]
[story_corpus.SR2_child.scenes.Iceberg]
stories = [ "sr2-session1-p004-story1", "sr2-session1-p006-story1", "sr2-session1-p007-story1", "sr2-session1-p009-story1", "sr2-session1-p015-story1", "sr2-session8-p004-story1", "sr2-session8-p006-story1", "sr2-session8-p007-story1"]
[story_corpus.SR2_child.scenes.Mars]
stories = [ "sr2-session2-p013-story1", "sr2-session3-p004a-story1", "sr2-session3-p006-story2", "sr2-session3-p007-story2", "sr2-session3-p009-story2", "sr2-session3-p010-story2", "sr2-session3-p013-1-story2", "sr2-session3-p015-story2", "sr2-session5-p004-story1", "sr2-session5-p006-story1", "sr2-session5-p007-story1", "sr2-session5-p009-story1", "sr2-session5-p010-story1", "sr2-session5-p011-story1", "sr2-session5-p013-story1", "sr2-session5-p015-story1"]
[story_corpus.SR2_child.scenes.PineForest]
stories = [ "sr2-session2-p004-story1", "sr2-session2-p006-story1", "sr2-session2-p007-story1", "sr2-session2-p009-story1", "sr2-session2-p015-story1", "sr2-session5-p004-story2", "sr2-session5-p006-story2", "sr2-session5-p007-story2", "sr2-session5-p011-story2", "sr2-session5-p013-story2", "sr2-session1-p013-story1"]
[story_corpus.SR2_child.scenes.Playground]
stories = [ "sr2-session1-p004-story2", "sr2-session1-p006-story2", "sr2-session1-p007-story2", "sr2-session1-p015-story2", "sr2-session4-p013-story2", "sr2-session8-p004-story2", "sr2-session8-p006-story2", "sr2-session8-p007-story2", "sr2-session8-p010-story2", "sr2-session8-p015-story2"]
[story_corpus.SR2_child.scenes.Treemeadow]
stories = [ "sr2-session4-p004-1-story2", "sr2-session4-p006-1-story2", "sr2-session4-p007-story2", "sr2-session4-p009-1-story2", "sr2-session6-p013-story1", "sr2-session7-p006-story1", "sr2-session7-p007-story1", "sr2-session7-p013-story1", "sr2-session7-p015-story1", "sr2-session8-p013-story1"]
