[p000]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "bob"

[p001]
story_retell_level = 2
story_create_level = 0
personalized = false
condition = "RR"
name = "alice"

[p002]
story_retell_level = 2
story_create_level = 1
personalized = true
condition = "NR"
name = "fred"

[p003]
story_retell_level = 3
story_create_level = 1
personalized = false
condition = "NR"
name = "ella"
