[p004]
name = "p004"
story_create_level = 0
story_retell_level = 1
personalized = false
condition = "NR"

[p005]
name = "p005"
story_create_level = 1
story_retell_level = 2
personalized = true
condition = "RR"

[p006]
name = "p006"
story_create_level = 0
story_retell_level = 1
personalized = false
condition = "NR"

[p007]
name = "p007"
story_create_level = 1
story_retell_level = 2
personalized = true
condition = "RR"

[p026]
name = "p026"
story_create_level = 1
fav_color = ""
story_retell_level = 3
personalized = false
condition = "NR"

[p001]
name = "p001"
story_create_level = 1
story_retell_level = 2
personalized = true
condition = "RR"

[p002]
name = "p002"
story_create_level = 1
story_retell_level = 2
personalized = false
condition = "NR"

[p003]
name = "p003"
story_create_level = 1
story_retell_level = 3
personalized = false
condition = "NR"

[p105]
name = "p105"
story_create_level = 1
fav_color = ""
story_retell_level = 2
personalized = false
condition = "NR"

[p104]
name = "p104"
story_create_level = 1
story_retell_level = 3
personalized = true
condition = "RR"

[p022]
name = "p022"
story_create_level = 0
fav_color = ""
story_retell_level = 1
personalized = false
condition = "NR"

[p029]
name = "p029"
story_create_level = 1
story_retell_level = 2
personalized = true
condition = "RR"

[p008]
name = "p008"
story_create_level = 1
story_retell_level = 3
personalized = false
condition = "NR"

[p009]
name = "p009"
story_create_level = 1
story_retell_level = 3
personalized = true
condition = "RR"

[p103]
name = "p103"
story_create_level = 1
fav_color = ""
story_retell_level = 3
personalized = false
condition = "NR"

[p102]
name = "p102"
story_create_level = 1
fav_color = ""
story_retell_level = 3
personalized = true
condition = "RR"

[p021]
name = "p021"
story_create_level = 1
fav_color = ""
story_retell_level = 3
personalized = true
condition = "RR"

[p027]
name = "p027"
story_create_level = 1
fav_color = ""
story_retell_level = 2
personalized = true
condition = "RR"

[p024]
name = "p024"
story_create_level = 1
story_retell_level = 3
personalized = false
condition = "NR"

[p023]
name = "p023"
story_create_level = 1
fav_color = ""
story_retell_level = 3
personalized = true
condition = "RR"

[p025]
name = "p025"
story_create_level = 1
fav_color = ""
story_retell_level = 3
personalized = true
condition = "RR"

[p028]
name = "p028"
story_create_level = 1
fav_color = ""
story_retell_level = 2
personalized = false
condition = "NR"

[p997]
name = "jackie"
story_create_level = 0
story_retell_level = 2
personalized = true
condition = "RR"

[p017]
name = "p017"
story_create_level = 1
story_retell_level = 3
personalized = true
condition = "RR"

[p016]
name = "p016"
story_create_level = 1
fav_color = ""
story_retell_level = 2
personalized = false
condition = "NR"

[p015]
name = "p015"
story_create_level = 1
fav_color = ""
story_retell_level = 3
personalized = true
condition = "RR"

[p014]
name = "p014"
story_create_level = 1
fav_color = ""
story_retell_level = 3
personalized = false
condition = "NR"

[p013]
name = "p013"
story_create_level = 1
fav_color = ""
story_retell_level = 3
personalized = true
condition = "RR"

[p012]
name = "p012"
story_create_level = 0
story_retell_level = 1
personalized = false
condition = "NR"

[p011]
name = "p011"
story_create_level = 1
story_retell_level = 3
personalized = true
condition = "RR"

[p010]
name = "p010"
story_create_level = 1
story_retell_level = 2
personalized = false
condition = "NR"

[p101]
name = "p101"
story_create_level = 1
fav_color = ""
story_retell_level = 3
personalized = false
condition = "NR"

[p031]
name = "p031"
story_create_level = 1
fav_color = ""
story_retell_level = 2
personalized = true
condition = "RR"

[p030]
name = "p030"
story_create_level = 1
story_retell_level = 3
personalized = false
condition = "NR"

[p019]
name = "p019"
story_create_level = 0
story_retell_level = 1
personalized = true
condition = "RR"

[p018]
name = "p018"
story_create_level = 1
story_retell_level = 2
personalized = false
condition = "NR"

[p020]
name = "p020"
story_create_level = 1
fav_color = ""
story_retell_level = 2
personalized = false
condition = "NR"

[p032]
name = "p032"
story_create_level = 1
story_retell_level = 3
personalized = false
condition = "NR"

[p998]
name = "jackie"
story_create_level = 1
story_retell_level = 2
personalized = false
condition = "NR"

[p999]
name = "jackie"
fav_color = "red"
story_create_level = 0
story_retell_level = 1
personalized = true
condition = "RR"

[p204]
name = "p204"
story_create_level = 1
story_retell_level = 2
personalized = false
condition = "NR"

[p205]
name = "p205"
story_create_level = 1
story_retell_level = 2
personalized = true
condition = "RR"

[p202]
name = "p202"
story_create_level = 1
story_retell_level = 3
personalized = false
condition = "NR"

[p203]
name = "p203"
story_create_level = 1
story_retell_level = 3
personalized = true
condition = "RR"

[p201]
name = "p201"
story_create_level = 0
story_retell_level = 1
personalized = true
condition = "RR"

[p307]
name = "p307"
story_create_level = 0
fav_color = "red"
story_retell_level = 1
personalized = true
condition = "RR"

[p306]
name = "p306"
story_create_level = 0
fav_color = "pink"
story_retell_level = 1
personalized = false
condition = "NR"

[p305]
name = "p305"
story_create_level = 1
fav_color = "red"
story_retell_level = 2
personalized = true
condition = "RR"

[p304]
name = "p304"
story_create_level = 0
fav_color = "blueAndBlack"
story_retell_level = 1
personalized = false
condition = "NR"

[p303]
name = "p303"
story_create_level = 0
fav_color = ""
story_retell_level = 1
personalized = true
condition = "RR"

[p302]
name = "p302"
story_create_level = 0
fav_color = "pink"
story_retell_level = 1
personalized = true
condition = "RR"

[p301]
name = "p301"
story_create_level = 0
fav_color = ""
story_retell_level = 1
personalized = false
condition = "NR"

[p020.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 1

[p015.2]
story_type = "create"
told_last_story = "TN"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SD"
story_level = 1

[p010.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p006.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p020.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p021.2]
story_type = "create"
told_last_story = "TN"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = ""
story_level = 1

[p021.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p306.3]
story_type = "create"
told_last_story = "TN"
leftover_scene = "Castle"
scenes = [ "Playground", "Castle",]
negotiation_outcome = "MyChoice"
last_story = "Iceberg"
liked_last_story = "SL"
story_level = 0

[p025.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p304.2]
story_type = "create"
scenes = [ "Iceberg", "Castle",]
story_level = 0

[p011.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p205.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p017.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p015.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p016.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p008.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p101.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 1

[p016.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 1

[p102.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 1

[p102.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p032.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p027.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p202.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p103.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SD"
story_level = 1

[p007.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p103.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p009.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p105.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p105.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 1

[p104.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p305.1]
story_type = "retell"
liked_story = ""
story_name = "baby_birds_first_nest"
told_story = ""

[p001.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p305.2]
story_type = "create"
scenes = [ "Iceberg", "Castle",]
story_level = 1

[p027.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 1

[p028.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 1

[p307.1]
story_type = "retell"
liked_story = "SD"
story_name = "baby_birds_first_nest"
told_story = "TN"

[p307.2]
story_type = "create"
scenes = [ "Iceberg", "Castle",]
story_level = 0

[p028.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p306.1]
story_type = "retell"
liked_story = "SL"
story_name = "baby_birds_first_nest"
told_story = "TN"

[p026.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p029.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p306.2]
story_type = "create"
scenes = [ "Iceberg", "Castle",]
story_level = 0

[p997.1]
story_type = "retell"
liked_story = "SD"
story_name = "baby_birds_first_nest"
told_story = "TY"

[p025.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 1

[p003.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p997.2]
story_type = "create"
scenes = [ "Castle", "Iceberg",]

[p014.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 1

[p014.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p998.2]
story_type = "create"
scenes = [ "Castle", "Iceberg",]

[p305.3]
story_type = "create"
told_last_story = "TN"
leftover_scene = "Iceberg"
scenes = [ "Playground", "Iceberg",]
negotiation_outcome = "MyChoice"
last_story = "Castle"
liked_last_story = "SL"
story_level = 1

[p998.1]
story_type = "retell"
liked_story = "SD"
story_name = "baby_birds_first_nest"
told_story = "TY"

[p304.3]
story_type = "create"
told_last_story = "TN"
leftover_scene = "Iceberg"
scenes = [ "Playground", "Iceberg",]
negotiation_outcome = "MyChoice"
last_story = "Castle"
liked_last_story = "SL"
story_level = 0

[p999.2]
story_type = "create"
scenes = [ "Castle", "Iceberg",]

[p999.3]
story_type = "create"
told_last_story = "TN"
leftover_scene = "Iceberg"
scenes = [ "Playground", "Iceberg",]
negotiation_outcome = "MyChoice"
last_story = "Castle"
liked_last_story = "SL"
story_level = 0

[p998.3]
story_type = "create"
told_last_story = "TY"
leftover_scene = "Castle"
scenes = [ "Playground", "Castle",]
negotiation_outcome = "YourChoice"
last_story = "Iceberg"
liked_last_story = "SD"
story_level = 0

[p999.1]
story_type = "retell"
liked_story = "SL"
story_name = "baby_birds_first_nest"
told_story = "TN"

[p002.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p022.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p022.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 0

[p204.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p005.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p031.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p031.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 1

[p023.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 1

[p018.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p024.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p304.1]
story_type = "retell"
liked_story = "SL"
story_name = "baby_birds_first_nest"
told_story = "TY"

[p307.3]
story_type = "create"
told_last_story = "TN"
leftover_scene = "Iceberg"
scenes = [ "Playground", "Iceberg",]
negotiation_outcome = "MyChoice"
last_story = "Castle"
liked_last_story = "SL"
story_level = 0

[p303.1]
story_type = "retell"
liked_story = "SL"
story_name = "baby_birds_first_nest"
told_story = "TN"

[p303.2]
story_type = "create"
told_last_story = "TN"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 0

[p004.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p030.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p019.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p201.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p012.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p301.2]
story_type = "create"
told_last_story = "TN"
leftover_scene = ""
last_story = ""
liked_last_story = "SL"
scenes = [ "Iceberg", "Castle",]
story_level = 0

[p026.2]
story_type = "create"
told_last_story = "TY"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 1

[p301.1]
story_type = "retell"
liked_story = "SL"
story_name = "baby_birds_first_nest"
told_story = "TN"

[p302.1]
story_type = "retell"
liked_story = "SL"
story_name = "baby_birds_first_nest"
told_story = "TN"

[p023.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p302.3]
story_type = "create"
told_last_story = "TN"
leftover_scene = "Castle"
scenes = [ "Playground", "Castle",]
negotiation_outcome = "MyChoice"
last_story = "Iceberg"
liked_last_story = "SL"
story_level = 0

[p302.2]
story_type = "create"
scenes = [ "Iceberg", "Castle",]
story_level = 0

[p203.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p013.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p013.2]
story_type = "create"
told_last_story = "TN"
leftover_scene = ""
scenes = [ "Iceberg", "Castle",]
last_story = ""
liked_last_story = "SL"
story_level = 1

[p101.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p016.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p015.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p101.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p105.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p021.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p998.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p997.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p303.2.stories]
Castle = "Castle-ReshmaParty-E"
Iceberg = "Iceberg-PenguinSlide-E"

[p103.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p307.2.stories]
Castle = "Castle-ReshmaParty-E"
Iceberg = "Iceberg-PenguinSlide-E"

[p302.2.stories]
Castle = "Castle-ReshmaParty-E"
Iceberg = "Iceberg-PenguinSlide-E"

[p301.2.stories]
Castle = "Castle-ReshmaParty-E"
Iceberg = "Iceberg-PenguinSlide-E"

[p013.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p305.3.stories]
Iceberg = "Iceberg-sr2-session8-p006-story1"
Playground = "Playground-sr2-session1-p007-story2"

[p022.2.stories]
Castle = "Castle-ReshmaParty-E"
Iceberg = "Iceberg-PenguinSlide-E"

[p999.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p028.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p027.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p102.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p304.3.stories]
Iceberg = "Iceberg-sr2-session8-p006-story1"
Playground = "Playground-sr2-session1-p007-story2"

[p023.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p020.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p031.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p014.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p304.2.stories]
Castle = "Castle-ReshmaParty-E"
Iceberg = "Iceberg-PenguinSlide-E"

[p026.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p302.3.stories]
Castle = "Castle-sr2-session2-p009-story2"
Playground = "Playground-sr2-session1-p007-story2"

[p307.3.stories]
Iceberg = "Iceberg-sr2-session8-p006-story1"
Playground = "Playground-sr2-session1-p007-story2"

[p025.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p306.2.stories]
Castle = "Castle-ReshmaParty-E"
Iceberg = "Iceberg-PenguinSlide-E"

[p305.2.stories]
Castle = "Castle-ReshmaParty-H"
Iceberg = "Iceberg-PenguinSlide-H"

[p306.3.stories]
Castle = "Castle-sr2-session2-p009-story2"
Playground = "Playground-sr2-session1-p007-story2"
