[p000]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"

[p001]
story_retell_level = 2
story_create_level = 0
personalized = false
condition = "RR"

[p002]
story_retell_level = 2
story_create_level = 1
personalized = true
condition = "NR"

[p003]
story_retell_level = 3
story_create_level = 1
personalized = false
condition = "NR"
