## Participants for testing purposes.
[p999]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "jackie"

[p998]
story_retell_level = 3
story_create_level = 1
personalized = false
condition = "NR"
name = "jackie"

[p997]
story_retell_level = 2
story_create_level = 0
personalized = true
condition = "RR"
name = "jackie"

## Lynch
[p001]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p001"

[p002]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p002"

[p003]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p003"

[p004]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p004"

[p005]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p005"

[p006]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p006"

[p007]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p007"

[p008]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p008"

[p009]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p009"

[p010]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p010"

[p011]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p011"

[p012]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p012"

[p013]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p013"

[p014]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p014"

[p015]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p015"

[p016]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p016"

[p017]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p017"

[p018]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p018"

[p019]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p019"

[p020]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p020"

[p021]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p021"

[p022]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p022"

[p023]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p023"

[p024]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p024"

[p025]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p025"

[p026]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p026"

[p027]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p027"

[p028]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p028"

[p029]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p029"

[p030]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p030"

[p031]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p031"

[p032]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p032"

## McGlynn
[p101]
story_retell_level = 3
story_create_level = 1
personalized = false
condition = "NR"
name = "p101"

[p102]
story_retell_level = 3
story_create_level = 1
personalized = true
condition = "RR"
name = "p102"

[p103]
story_retell_level = 3
story_create_level = 1
personalized = false
condition = "NR"
name = "p103"

[p104]
story_retell_level = 3
story_create_level = 1
personalized = true
condition = "RR"
name = "p104"

[p105]
story_retell_level = 2
story_create_level = 1
personalized = false
condition = "NR"
name = "p105"

## Graceworks
[p201]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p201"

[p202]
story_retell_level = 3
story_create_level = 1
personalized = false
condition = "NR"
name = "p202"

[p203]
story_retell_level = 3
story_create_level = 1
personalized = true
condition = "RR"
name = "p203"

[p204]
story_retell_level = 2
story_create_level = 1
personalized = false
condition = "NR"
name = "p204"

[p205]
story_retell_level = 2
story_create_level = 1
personalized = true
condition = "RR"
name = "p205"


## Make Way For Kids
[p301]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p301"

[p302]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p302"

[p303]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p303"

[p304]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p304"

[p305]
story_retell_level = 2
story_create_level = 1
personalized = true
condition = "RR"
name = "p305"

[p306]
story_retell_level = 1
story_create_level = 0
personalized = false
condition = "NR"
name = "p306"

[p307]
story_retell_level = 1
story_create_level = 0
personalized = true
condition = "RR"
name = "p307"

## Session 1
## Test participants
[p997.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p998.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p999.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

## Lynch
[p001.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p002.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p003.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p004.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p005.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p006.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p007.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p008.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p009.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p010.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p011.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p012.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p013.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p014.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p015.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p016.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p017.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p018.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p019.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p020.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p021.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p022.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p023.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p024.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p025.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p026.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p027.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p028.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p029.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p030.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p031.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p032.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

## McGlynn
[p101.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p102.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p103.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p104.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p105.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

## Graceworks
[p201.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p202.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p203.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p204.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p205.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

## MWFK
[p301.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p302.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p303.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p304.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p305.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p306.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

[p307.1]
story_type = "retell"
story_name = "baby_birds_first_nest"

## Session 2 - some will be generated, some we will need to add!
