pid = "p000"
session = 2
stories_heard = ["PenguinSlide"]
stories_heard_levels = [0]
scenes_shown = ["Iceberg", "Treemeadow"]
scenes_used = ["Iceberg"]
story_text = ["I want it to be about a snowman. Once upon a time there was a snowman. And he was alive. He lived in the North Pole. And one day he went for a walk. His hat fell off. He put it back on. Then he met a penguin. He was talking with his other friend, a penguin. And they had a walk together. The end."]
