pid = "p001"
session = 4
stories_heard = ["Treemeadow-sr2-session6-p013-story1"]
stories_heard_levels = [0]
scenes_shown = ["Treemeadow", "Playground"]
scenes_used = ["Playground"]
story_text = ["Once upon a time there was two great friends that was a brother and a sister. And one day, they met  a dragon. And he was nice. But he was actually not nice.  So they played with him.  And he let out some fire from his mouth.  And then they all fell to the ground.  But when the moms and dads heard that  they followed the sound. And when they saw their kids  they were almost dead.  So they ran home as fast as they could and then back.  And they got knight suits. So they won't get hurt from the dragon. The end."]
