pid = "p001"
session = 2
stories_heard = ["PenguinSlide"]
stories_heard_levels = [0]
scenes_shown = ["Iceberg", "Treemeadow"]
scenes_used = ["Iceberg"]
story_text = ["Once upon a time there were two little penguins. One was named Heather. And one was named Jason. They both lived together on the top of Iceberg Canyon. One day, their friend Sealy came over to play. She was afraid to slide down the mountain like those two penguins. Sometimes the sun grew bigger and bigger and hotter and hotter in the days. So, the ice melted. And they could play in the soft, green snow. One day, Heather, who was the bigger penguin,  liked to slide down a big ice pole. Then  it was Heathers turn. She slid down, head first.  And then Sealy, the seal, slid down and landed on their heads. Then she went home. Then the two penguins went home together. And they lived behind a bush. The end."]
