pid = "p003"
session = 2
stories_heard = ["PenguinSlide"]
stories_heard_levels = [1]
scenes_shown = ["Iceberg", "Treemeadow"]
scenes_used = ["Iceberg"]
story_text = ["I'm gonna tell a story about a snowman. Once upon a time there were two penguin sisters. One lived on the top of the  sister. But one had power. And then one day they made a snowman together. And then the big sister  turned the whole house into wintertime. Then she went back into her room. And the little sister played. And then she went back to her room. The end."]
