[p000]
story_retell_level = 0
story_create_level = 0

[p001]
story_retell_level = 1
story_create_level = 0

[p002]
story_retell_level = 1
story_create_level = 1

[p003]
story_retell_level = 2
story_create_level = 1

[p003.overall]
scenes_used = [ "Treemeadow",]
stories_heard_levels = [ 1, 0,]
stories_heard = [ "Treemeadow-sr2-session7-p006-story1",]

[p000.overall]
scenes_used = [ "Castle", "Playground",]
stories_heard_levels = [ 0, 0,]
stories_heard = [ "Castle-ReshmaParty-E", "Playground-sr2-session1-p015-story2",]

[p001.overall]
scenes_used = [ "Playground",]
stories_heard_levels = [ 0,]
stories_heard = [ "Treemeadow-sr2-session6-p013-story1",]

[p002.overall]
scenes_used = [ "Iceberg",]
stories_heard_levels = [ 0,]
stories_heard = [ "Iceberg-sr2-session1-p015-story1",]

[p003.session.4]
story_text = [ "Once upon a time there was two great friends that was a brother and a sister. And one day, they met  a dragon. And he was nice. But he was actually not nice.  So they played with him.  And he let out some fire from his mouth.  And then they all fell to the ground.  But when the moms and dads heard that  they followed the sound. And when they saw their kids  they were almost dead.  So they ran home as fast as they could and then back.  And they got knight suits. So they won't get hurt from the dragon. The end.",]
scenes_used = [ "Treemeadow",]
stories_heard_levels = [ 1, 0,]
scenes_shown = [ "Treemeadow", "Playground",]
stories_heard = [ "Treemeadow-sr2-session7-p006-story1",]

[p000.session.4]
story_text = [ "One day  Michael wanted to play on the swing. So he went back and forth, back and forth. She swung a little too high and landed on the slide and slid down. She landed on the boxes and climbed up. She found a yellow ball. And she gave the ball to Mike and then to Rose and then to her. She went to the swing.  Both girls thought it was a good idea to swing on balls. They swung and swung and swung. And this ball swung the highest. Then she flew into a tree, poof poof  and slid out. And  they played hopscotch and climbed up the steps. Catch.  And she gave it to him when she gave it to her. She climbed down and went down the slide again. She took the ball with her up the boxes. And he said, Give us back our ball. No, she said. There's a ball on your head. I can't balance a ball on my head. Poor Rose. So give us our ball. Alright. I'll give you your ball as long as you let me have the blue one. So they played catch. The end",]
scenes_used = [ "Playground",]
stories_heard_levels = [ 0,]
scenes_shown = [ "Playground", "Treemeadow",]
stories_heard = [ "Playground-sr2-session1-p015-story2",]

[p002.session.4]
story_text = [ "Once upon a time there were two little penguins. One was named Heather. And one was named Jason. They both lived together on the top of Iceberg Canyon. One day, their friend Sealy came over to play. She was afraid to slide down the mountain like those two penguins. Sometimes the sun grew bigger and bigger and hotter and hotter in the days. So, the ice melted. And they could play in the soft, green snow. One day, Heather, who was the bigger penguin,  liked to slide down a big ice pole. Then  it was Heathers turn. She slid down, head first.  And then Sealy, the seal, slid down and landed on their heads. Then she went home. Then the two penguins went home together. And they lived behind a bush. The end.",]
scenes_used = [ "Iceberg",]
stories_heard_levels = [ 0,]
scenes_shown = [ "Iceberg", "Playground",]
stories_heard = [ "Iceberg-sr2-session1-p015-story1",]

[p000.session.3]
scenes_used = [ "Castle",]
stories_heard = [ "Castle-ReshmaParty-E",]
stories_heard_levels = [ 0,]
story_text = [ "One day  Michael wanted to play on the swing. So he went back and forth, back and forth. She swung a little too high and landed on the slide and slid down. She landed on the boxes and climbed up. She found a yellow ball. And she gave the ball to Mike and then to Rose and then to her. She went to the swing.  Both girls thought it was a good idea to swing on balls. They swung and swung and swung. And this ball swung the highest. Then she flew into a tree, poof poof  and slid out. And  they played hopscotch and climbed up the steps. Catch.  And she gave it to him when she gave it to her. She climbed down and went down the slide again. She took the ball with her up the boxes. And he said, Give us back our ball. No, she said. There's a ball on your head. I can't balance a ball on my head. Poor Rose. So give us our ball. Alright. I'll give you your ball as long as you let me have the blue one. So they played catch. The end",]
scenes_shown = [ "Playground", "Castle",]

[p001.session.4]
story_text = [ "Once upon a time there was two great friends that was a brother and a sister. And one day, they met  a dragon. And he was nice. But he was actually not nice.  So they played with him.  And he let out some fire from his mouth.  And then they all fell to the ground.  But when the moms and dads heard that  they followed the sound. And when they saw their kids  they were almost dead.  So they ran home as fast as they could and then back.  And they got knight suits. So they won't get hurt from the dragon. The end.",]
scenes_used = [ "Playground",]
stories_heard_levels = [ 0,]
scenes_shown = [ "Treemeadow", "Playground",]
stories_heard = [ "Treemeadow-sr2-session6-p013-story1",]
